import Head from 'next/head'
import { Inter } from '@next/font/google'
import Review from '@/Components/Review/Review'
import BestSeller from '@/Components/BestSellers/BestSellers'
import Trending from '@/Components/Trending/Trending'
import RecentlyAdded from '@/Components/RecentlyAdded/RecentlyAdded'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <BestSeller></BestSeller>
        <Trending></Trending>
        <RecentlyAdded></RecentlyAdded>
        <Review></Review>
      </main>
    </>
  )
}
